"""Initial schema with killmail_raw, fit, item_type, fit_aggregate_daily

Revision ID: 61972fc91991
Revises:
Create Date: 2025-11-14 07:45:10.722654

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "61972fc91991"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fit_aggregate_daily",
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("ship_type_id", sa.BigInteger(), nullable=False),
        sa.Column("fit_signature", sa.String(length=128), nullable=False),
        sa.Column("loss_count", sa.Integer(), nullable=False),
        sa.Column(
            "last_updated",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("date", "ship_type_id", "fit_signature"),
        sa.UniqueConstraint("date", "ship_type_id", "fit_signature", name="uq_daily_agg"),
    )
    op.create_table(
        "item_type",
        sa.Column("type_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("group_id", sa.BigInteger(), nullable=True),
        sa.Column("category_id", sa.BigInteger(), nullable=True),
        sa.Column("metagroup_id", sa.Integer(), nullable=True),
        sa.Column("slot_hint", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("type_id"),
    )
    op.create_index(op.f("ix_item_type_type_id"), "item_type", ["type_id"], unique=False)
    op.create_table(
        "killmail_raw",
        sa.Column("killmail_id", sa.BigInteger(), nullable=False),
        sa.Column("killmail_hash", sa.String(length=64), nullable=False),
        sa.Column("kill_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("solar_system_id", sa.BigInteger(), nullable=True),
        sa.Column("victim_ship_type_id", sa.BigInteger(), nullable=True),
        sa.Column("json", sa.JSON(), nullable=False),
        sa.Column(
            "ingested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("killmail_id"),
    )
    op.create_index(
        op.f("ix_killmail_raw_killmail_hash"), "killmail_raw", ["killmail_hash"], unique=False
    )
    op.create_index(
        op.f("ix_killmail_raw_killmail_id"), "killmail_raw", ["killmail_id"], unique=False
    )
    op.create_table(
        "fit",
        sa.Column("fit_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("killmail_id", sa.BigInteger(), nullable=False),
        sa.Column("ship_type_id", sa.BigInteger(), nullable=False),
        sa.Column("fit_signature", sa.String(length=128), nullable=False),
        sa.Column("slot_counts", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["killmail_id"],
            ["killmail_raw.killmail_id"],
        ),
        sa.PrimaryKeyConstraint("fit_id"),
    )
    op.create_index(op.f("ix_fit_fit_id"), "fit", ["fit_id"], unique=False)
    op.create_index(op.f("ix_fit_fit_signature"), "fit", ["fit_signature"], unique=False)
    op.create_index(op.f("ix_fit_killmail_id"), "fit", ["killmail_id"], unique=False)
    op.create_index(op.f("ix_fit_ship_type_id"), "fit", ["ship_type_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fit_ship_type_id"), table_name="fit")
    op.drop_index(op.f("ix_fit_killmail_id"), table_name="fit")
    op.drop_index(op.f("ix_fit_fit_signature"), table_name="fit")
    op.drop_index(op.f("ix_fit_fit_id"), table_name="fit")
    op.drop_table("fit")
    op.drop_index(op.f("ix_killmail_raw_killmail_id"), table_name="killmail_raw")
    op.drop_index(op.f("ix_killmail_raw_killmail_hash"), table_name="killmail_raw")
    op.drop_table("killmail_raw")
    op.drop_index(op.f("ix_item_type_type_id"), table_name="item_type")
    op.drop_table("item_type")
    op.drop_table("fit_aggregate_daily")
    # ### end Alembic commands ###
