"""add universe tables for regions, constellations, and solar systems

Revision ID: aa715a4f50e9
Revises: 61972fc91991
Create Date: 2025-11-14 17:03:23.178908

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "aa715a4f50e9"
down_revision = "61972fc91991"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "region",
        sa.Column("region_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("region_id"),
    )
    op.create_index(op.f("ix_region_name"), "region", ["name"], unique=False)
    op.create_index(op.f("ix_region_region_id"), "region", ["region_id"], unique=False)
    op.create_table(
        "constellation",
        sa.Column("constellation_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("region_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["region.region_id"],
        ),
        sa.PrimaryKeyConstraint("constellation_id"),
    )
    op.create_index(
        op.f("ix_constellation_constellation_id"),
        "constellation",
        ["constellation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_constellation_name"), "constellation", ["name"], unique=False)
    op.create_index(
        op.f("ix_constellation_region_id"), "constellation", ["region_id"], unique=False
    )
    op.create_table(
        "solar_system",
        sa.Column("system_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("constellation_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["constellation_id"],
            ["constellation.constellation_id"],
        ),
        sa.PrimaryKeyConstraint("system_id"),
    )
    op.create_index(
        op.f("ix_solar_system_constellation_id"), "solar_system", ["constellation_id"], unique=False
    )
    op.create_index(op.f("ix_solar_system_name"), "solar_system", ["name"], unique=False)
    op.create_index(op.f("ix_solar_system_system_id"), "solar_system", ["system_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_solar_system_system_id"), table_name="solar_system")
    op.drop_index(op.f("ix_solar_system_name"), table_name="solar_system")
    op.drop_index(op.f("ix_solar_system_constellation_id"), table_name="solar_system")
    op.drop_table("solar_system")
    op.drop_index(op.f("ix_constellation_region_id"), table_name="constellation")
    op.drop_index(op.f("ix_constellation_name"), table_name="constellation")
    op.drop_index(op.f("ix_constellation_constellation_id"), table_name="constellation")
    op.drop_table("constellation")
    op.drop_index(op.f("ix_region_region_id"), table_name="region")
    op.drop_index(op.f("ix_region_name"), table_name="region")
    op.drop_table("region")
    # ### end Alembic commands ###
